DROP TABLE IF EXISTS log_logins;
CREATE TABLE log_logins (
  loginstamp timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  userid varchar(1000) NOT NULL,
  spentityid varchar(1000) DEFAULT NULL,
  idpentityid varchar(1000) DEFAULT NULL,
  spentityname varchar(1000) DEFAULT NULL,
  idpentityname varchar(1000) DEFAULT NULL,
  useragent varchar(1024) DEFAULT NULL,
  voname varchar(1024) DEFAULT NULL,
  id bigint generated by default as identity (start with 20000),
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS aggregated_log_logins;
CREATE TABLE aggregated_log_logins (
  entryday date NOT NULL,
  spentityid varchar(1000) DEFAULT NULL,
  idpentityid varchar(1000) DEFAULT NULL,
  spentityname varchar(1000) DEFAULT NULL,
  idpentityname varchar(1000) DEFAULT NULL,
  entrycount bigint NOT NULL,
  datespidphash varchar(100) NOT NULL,
  id bigint generated by default as identity (start with 20000),
  PRIMARY KEY (id),
  UNIQUE (datespidphash)
);

DROP TABLE IF EXISTS aggregate_meta_data;
CREATE TABLE aggregate_meta_data (
  aggregatepoint bigint NOT NULL,
  active BIT DEFAULT 0
);

DROP TABLE IF EXISTS user_log_logins;
CREATE TABLE user_log_logins (
  loginstamp timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  userid varchar(1000) NOT NULL,
  spentityid varchar(1000) DEFAULT NULL,
  spentityname varchar(1000) DEFAULT NULL,
  idpentityid varchar(1000) DEFAULT NULL,
  usersphash varchar(40) NOT NULL,
  id bigint generated by default as identity (start with 20000),
  PRIMARY KEY (id),
  UNIQUE (usersphash)
);

DROP TABLE IF EXISTS user_unique_logins;
CREATE TABLE user_unique_logins (
  spentityid varchar(1000) DEFAULT NULL,
  idpentityid varchar(1000) DEFAULT NULL,
  entrycount bigint NOT NULL,
  timespan integer NOT NULL,
  month integer DEFAULT NULL,
  year integer DEFAULT NULL
);

DROP TABLE IF EXISTS user_unique_logins_cache;
CREATE TABLE user_unique_logins_cache (
  userid varchar(1000) NOT NULL,
  spentityid varchar(1000) DEFAULT NULL,
  idpentityid varchar(1000) DEFAULT NULL,
  timespan integer NOT NULL,
  month integer DEFAULT NULL,
  year integer DEFAULT NULL
);

INSERT INTO aggregate_meta_data (aggregatepoint)
  VALUES (0);
  
  
INSERT INTO log_logins (loginstamp, userid, spentityid, idpentityid)
  VALUES ('2012-04-18 11:48:41','idp1:user_1', 'sp1', 'idp1');
INSERT INTO log_logins (loginstamp, userid, spentityid, idpentityid)
  VALUES ('2012-04-19 11:48:41','idp2:user_1', 'sp2', 'idp2');
INSERT INTO log_logins (loginstamp, userid, spentityid, idpentityid)
  VALUES ('2012-03-19 11:48:42','idp2:user_1', 'sp2', 'idp2');
INSERT INTO log_logins (loginstamp, userid, spentityid, idpentityid)
  VALUES ('2012-04-20 11:48:41','idp2:user_1', 'sp1', 'idp2');
INSERT INTO log_logins (loginstamp, userid, spentityid, idpentityid)
  VALUES ('2012-02-20 11:48:42','idp2:user_1', 'sp1', 'idp2');
INSERT INTO log_logins (loginstamp, userid, spentityid, idpentityid)
  VALUES ('2012-04-20 11:48:41','idp2:user_2', 'sp3', 'idp2');
INSERT INTO log_logins (loginstamp, userid, spentityid, idpentityid)
  VALUES ('2012-04-21 11:48:41','idp2:user_3', 'sp1', 'idp2');
INSERT INTO log_logins (loginstamp, userid, spentityid, idpentityid)
  VALUES ('2012-04-21 11:48:41','idp2:user_4', 'sp1', 'idp2');
INSERT INTO log_logins (loginstamp, userid, spentityid, idpentityid)
  VALUES ('2012-04-21 11:48:41','idp3:user_4', 'sp2', 'idp3');
INSERT INTO log_logins (loginstamp, userid, spentityid, idpentityid)
  VALUES ('2012-04-22 11:48:41','idp3:user_4', 'sp3', 'idp3');

  
  

INSERT INTO aggregated_log_logins (entryday, spentityid, spentityname, idpentityid, idpentityname, entrycount, datespidphash)
  VALUES('2013-01-01', 'sp1', 'sp1_name', 'idp1', 'idp1_name', 20, 1);
INSERT INTO aggregated_log_logins (entryday, spentityid, spentityname, idpentityid, idpentityname, entrycount, datespidphash)
  VALUES('2013-01-02', 'sp1', 'sp1_name','idp1','idp1_name', 20, 2);
INSERT INTO aggregated_log_logins (entryday, spentityid, spentityname, idpentityid, idpentityname, entrycount, datespidphash)
  VALUES('2013-01-03', 'sp1', 'sp1_name','idp1','idp1_name', 20, 3);
INSERT INTO aggregated_log_logins (entryday, spentityid, spentityname, idpentityid, idpentityname, entrycount, datespidphash)
  VALUES('2013-01-04', 'sp1', 'sp1_name','idp1','idp1_name', 20, 4);
INSERT INTO aggregated_log_logins (entryday, spentityid, spentityname, idpentityid, idpentityname, entrycount, datespidphash)
  VALUES('2013-01-05', 'sp1', 'sp1_name','idp1','idp1_name', 20, 5);
INSERT INTO aggregated_log_logins (entryday, spentityid, spentityname, idpentityid, idpentityname, entrycount, datespidphash)
  VALUES('2013-01-06', 'sp1', 'sp1_name','idp1','idp1_name', 20, 6);
INSERT INTO aggregated_log_logins (entryday, spentityid, spentityname, idpentityid, idpentityname, entrycount, datespidphash)
  VALUES('2013-01-07', 'sp1', 'sp1_name','idp1','idp1_name', 20, 7);
INSERT INTO aggregated_log_logins (entryday, spentityid, spentityname, idpentityid, idpentityname, entrycount, datespidphash)
  VALUES('2013-01-08', 'sp1', 'sp1_name','idp1','idp1_name', 20, 8);
INSERT INTO aggregated_log_logins (entryday, spentityid, spentityname, idpentityid, idpentityname, entrycount, datespidphash)
  VALUES('2013-01-09', 'sp1', 'sp1_name','idp1','idp1_name', 20, 9);
INSERT INTO aggregated_log_logins (entryday, spentityid, spentityname, idpentityid, idpentityname, entrycount, datespidphash)
  VALUES('2013-01-10', 'sp1', 'sp1_name','idp1','idp1_name', 20, 10);
INSERT INTO aggregated_log_logins (entryday, spentityid, spentityname, idpentityid, idpentityname, entrycount, datespidphash)
  VALUES('2013-01-11', 'sp1', 'sp1_name','idp1','idp1_name', 20, 11);
INSERT INTO aggregated_log_logins (entryday, spentityid, spentityname, idpentityid, idpentityname, entrycount, datespidphash)
  VALUES('2013-01-12', 'sp1', 'sp1_name','idp1','idp1_name', 20, 12);

INSERT INTO aggregated_log_logins (entryday, spentityid, spentityname, idpentityid, idpentityname, entrycount, datespidphash)
  VALUES('2013-01-01', 'sp2', 'sp2_name','idp1','idp1_name', 20, 13);
INSERT INTO aggregated_log_logins (entryday, spentityid, spentityname, idpentityid, idpentityname, entrycount, datespidphash)
  VALUES('2013-01-02', 'sp2', 'sp2_name','idp1','idp1_name', 20, 14);
INSERT INTO aggregated_log_logins (entryday, spentityid, spentityname, idpentityid, idpentityname, entrycount, datespidphash)
  VALUES('2013-01-03', 'sp2', 'sp2_name','idp1','idp1_name', 20, 15);
INSERT INTO aggregated_log_logins (entryday, spentityid, spentityname, idpentityid, idpentityname, entrycount, datespidphash)
  VALUES('2013-01-04', 'sp2', 'sp2_name','idp1','idp1_name', 20, 16);
INSERT INTO aggregated_log_logins (entryday, spentityid, spentityname, idpentityid, idpentityname, entrycount, datespidphash)
  VALUES('2013-01-05', 'sp2', 'sp2_name','idp1', 'idp1_name',20, 17);
INSERT INTO aggregated_log_logins (entryday, spentityid, spentityname, idpentityid, idpentityname, entrycount, datespidphash)
  VALUES('2013-01-06', 'sp2', 'sp2_name','idp1','idp1_name', 20, 18);
INSERT INTO aggregated_log_logins (entryday, spentityid, spentityname, idpentityid, idpentityname, entrycount, datespidphash)
  VALUES('2013-01-07', 'sp1', 'sp1_name','idp2','idp2_name', 20, 19);
INSERT INTO aggregated_log_logins (entryday, spentityid, spentityname, idpentityid, idpentityname, entrycount, datespidphash)
  VALUES('2013-01-08', 'sp1', 'sp1_name','idp2','idp2_name', 20, 20);
INSERT INTO aggregated_log_logins (entryday, spentityid, spentityname, idpentityid, idpentityname, entrycount, datespidphash)
  VALUES('2013-01-09', 'sp1', 'sp1_name','idp2','idp2_name', 20, 21);
INSERT INTO aggregated_log_logins (entryday, spentityid, spentityname, idpentityid, idpentityname, entrycount, datespidphash)
  VALUES('2013-01-10', 'sp1', 'sp1_name','idp2','idp2_name', 20, 22);
INSERT INTO aggregated_log_logins (entryday, spentityid, spentityname, idpentityid, idpentityname, entrycount, datespidphash)
  VALUES('2013-01-11', 'sp1', 'sp1_name','idp2','idp2_name', 20, 23);
INSERT INTO aggregated_log_logins (entryday, spentityid, spentityname, idpentityid, idpentityname, entrycount, datespidphash)
  VALUES('2013-01-12', 'sp1', 'sp1_name','idp2','idp2_name', 20, 24);

-- This is dirty as we insert rows with the same date, sp and idp (which in real life should not happen)
INSERT INTO aggregated_log_logins (entryday, spentityid, spentityname, idpentityid, idpentityname, entrycount, datespidphash)
  VALUES('2013-01-12', 'sp1', 'sp1_name','idp2','idp2_name', 10, 25);
INSERT INTO aggregated_log_logins (entryday, spentityid, spentityname, idpentityid, idpentityname, entrycount, datespidphash)
  VALUES('2013-01-12', 'sp1', 'sp1_name','idp2','idp2_name', 15, 26);
INSERT INTO aggregated_log_logins (entryday, spentityid, spentityname, idpentityid, idpentityname, entrycount, datespidphash)
  VALUES('2014-01-12', 'sp1', 'sp1_name','idp2','idp2_name', 10, 27);


-- insert user log logins
INSERT INTO user_log_logins (loginstamp, userid, spentityid, idpentityid, usersphash)
  VALUES ('2012-01-01 01:00:00', 'user1', 'sp1', 'idp1', 'user1sp1idp1');
INSERT INTO user_log_logins (loginstamp, userid, spentityid, idpentityid, usersphash)
  VALUES ('2012-01-01 01:00:00', 'user2', 'sp1', 'idp1', 'user2sp1idp1');